name: Create Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # <-- Diese Zeile ist entscheidend!
    steps:
      - uses: actions/checkout@v3
      
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep "Version: " nodelist.php | awk '{print $3}')
          IFS='.' read -r MAJOR MINOR BUILD <<< "$VERSION"
          NEW_BUILD=$((BUILD + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_BUILD"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
      - name: Update version
        run: |
          sed -i "s/Version: .*/Version: $NEW_VERSION/" nodelist.php
          
      - name: Create zip
        run: zip -r nodelist-plugin.zip . -x "*.git*"
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          body: Auto-generated release
          draft: false
          prerelease: false
          files: nodelist-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
